version: "1"
networks:
  dev:

services:
  rabbit_mq:
    image: rabbitmq:3.10.7-management
    container_name: rabbit_mq
    hostname: rabbit_mq
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    networks:
      - dev
    restart: always

  core:
    container_name: core_uuid_generator
    environment:
      - RABBIT_LOGIN=rmuser
      - RABBIT_PASSWORD=rmpassword
      - RABBIT_HOST=rabbit_mq
    build:
      context: ./src/core
      additional_contexts:
        for_requirements: ./
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./core:/usr/src/app/core
    depends_on:
        - rabbit_mq
    networks:
      - dev
    restart: always

  consumer:
    container_name: comsumer_uuid_generator
    environment:
      - RABBIT_LOGIN=rmuser
      - RABBIT_PASSWORD=rmpassword
      - RABBIT_HOST=rabbit_mq
    build:
      context: ./src/consumer
    depends_on:
        - rabbit_mq
    volumes:
      - ./consumer:/usr/src/app/consumer
    networks:
      - dev
    restart: always
