version: "1"

services:
  rabbit_mq:
    image: rabbitmq:3.8-rc-management
    container_name: rabbit_mq_rc
    ports:
        - '5672:5672'
        - '15672:15672'
    volumes:
      - rabbit_mqdata:/usr/share/rabbitmq/data
  producer:
    build: .
    depends_on:
        - rabbit_mq
    environment:
        AMQP_URL: 'amqp://rabbit_mq?connection_attempts=10&retry_delay=10'
    volumes:
      - ./producer:/usr/src/app/producer
  consumer:
    build: src
    depends_on:
        - rabbit_mq
    environment:
        AMQP_URL: 'amqp://rabbit_mq?connection_attempts=10&retry_delay=10'
    volumes:
      - ./consumer:/usr/src/app/consumer
volumes:
    rabbit_mqdata:
      driver: local
