version: "1"
networks:
  net:

services:
  rabbit_mq:
    image: rabbitmq:3.10.7-management
    container_name: rabbit_mq
    hostname: rabbit_mq
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    networks:
      - net
    restart: always

  uuid_generator:
    container_name: uuid_generator
    environment:
      - RABBIT_LOGIN=rmuser
      - RABBIT_PASSWORD=rmpassword
      - RABBIT_HOST=rabbit_mq
    build:
      context: ./src
      additional_contexts:
        for_requirements: ./
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./uuid_generator:/usr/src/app/uuid_generator
    depends_on:
        - rabbit_mq
    networks:
      - net
    restart: always
